Create Fermions_in_double_well_qiskit.ipynb
Qiskit-Extensions/qiskit-cold-atom pull request #13
Opened 2021-10-22 15:10 UTC by fretchen

Attached you can find one tutorial on experiments in the Jochim group that I prepared for teaching. I am not sure how it fits into the series of tutorials, but it might be nicely integrated ...

2021-11-23 09:04 UTC, eggerdj requested changes
Overall this is looking good but we need more description of what is going on. The biggest change needed is more description to guide the user through the tutorial. Here are some additional changes we should implement:
* Add title of the paper in the introduction text. This text also has some typos.
* Feels unnecessary to have black formatting on the data.
* Add a description of the first plot. What are we seeing?
* scipy import is randomly placed in the NB.
* Analytical prediction: write out what $|L\rangle$ and R stand for. State what this section is doing. E.g. "Here we numerically solve the dynamics of the system by exponentiating the Hamiltonian.". Perhaps we can package this calculation into a small function so that you can do:
```
ax1.plot(t_analytical * 1e3, solve_dynamics(U=0), "r-", label="U = 0", linewidth=4, alpha=0.5)
ax2.plot(t_analytical * 1e3, solve_dynamics(U=J), "b-", label="U = J", linewidth=4, alpha=0.5)
```
* Are the labels correct since you write `U = 0.7 * J;` in one of the cells?
* Describe the plot in the analytic section.
* After the analytic section we start building circuit. We should state that we are doing this and why. E.g. "We now show that the experiment presented above can be described in a circuit language using Qiskit cold atom. To do this we will need a quantum circuit with two registers of four modes each to describe ... . We first must load the fermions into the tweezers, see tutorial XX for details. The fully dynamics is contained in one gate, i.e. the `FermiHubbard` gate, that encapsulates the system's dynamics."
* The plot in output 18 needs a description and labels. E.g. we see hopping, the simulation and the data from Selim match, etc.
* Language: `As you can see the back-end is only implementation a limited set of back-ends such that the full circuit has to be trotterized.`
* Add comment describing the variables, e.g. 
```
# Variable description
J = ...

# Variable description
U = 0.7 * J
```

2021-12-07 15:02 UTC, LaurinFischer commented
I have now reworked the Qiskit part of the notebook to make full use of the functionalities provided by the package.

2021-12-07 19:41 UTC, eggerdj requested changes
Looks awesome. A few minor typos.

2021-12-07 19:41 UTC, eggerdj commented on docs/tutorials/08_fermions_in_double_well.ipynb
> +    "These dynamics have an intuitive explanation: Without interaction, both atoms tunnel back and forth between $|L\\rangle$ and $|R\\langle$ at the same rate, which leads to sinusoidal interactions
```suggestion
    "These dynamics have an intuitive explanation: Without interaction, both atoms tunnel back and forth between $|L\\rangle$ and $|R\\rangle$ at the same rate, which leads to sinusoidal interactions. With interaction, the atoms repel each other (as $U>0$) whichs forms a complicated beating pattern of the tunneling. "
```

2021-12-07 19:41 UTC, eggerdj commented on docs/tutorials/08_fermions_in_double_well.ipynb
> +    "To directly simulate the experiment, we can define the measured observable and the run a list of circuits with different evolution times on the simulator backend. "
```suggestion
    "To directly simulate the experiment, we can define the measured observable and then run a list of circuits with different evolution times on the simulator backend. "
```

2021-12-07 19:41 UTC, eggerdj commented on docs/tutorials/08_fermions_in_double_well.ipynb
> +    "Let's compare the qiskit's simulations to the experimental data and the numerical model from above:"
```suggestion
    "Let's compare the Qiskit simulations to the experimental data and the numerical model from above:"
```

2021-12-07 19:41 UTC, eggerdj commented on docs/tutorials/08_fermions_in_double_well.ipynb
> +      "image/png": "iVBORw0KGgoAAAANSUhEUgAABMAAAAOACAYAAADctQ90AAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjMuNCwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy8QVMy6AAAACXBIWXMAAAsTAAALEwEAmpwYAACFnElEQVR4nOz
```suggestion
    "You will now have to save the job and wait until the job status changes to done. "
```

2021-12-07 19:47 UTC, LaurinFischer commented on docs/tutorials/08_fermions_in_double_well.ipynb
> +      "image/png": "iVBORw0KGgoAAAANSUhEUgAABMAAAAOACAYAAADctQ90AAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjMuNCwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy8QVMy6AAAACXBIWXMAAAsTAAALEwEAmpwYAACFnElEQVR4nOz
addressed in fd7f90d

2021-12-07 20:12 UTC, eggerdj approved these changes
LGTM!

2021-12-08 09:35 UTC, merged