Gate library and example for synqs fermion backend
Qiskit-Extensions/qiskit-cold-atom pull request #16
Opened 2021-11-16 12:52 UTC by RohitPrasadBhatt

This allows for using our fermion backend.

2021-11-21 07:52 UTC, eggerdj requested changes
Looks like this PR should be combined with https://github.com/Qiskit-Extensions/qiskit-cold-atom/pull/13 so that we have the choice over the backend.

2021-11-21 07:52 UTC, eggerdj commented on qiskit_cold_atom/synqs_fermions/fqs_gate_library.py
> +class HopGate(Gate):
How does this relate to the existing fermion gates https://github.com/Qiskit-Extensions/qiskit-cold-atom/blob/410332a470ad371eab0cb74c2b88ee39aae1b887/qiskit_cold_atom/fermions/fermion_gate_library.py#L342 ? We should try and use those as much as possible.

2021-11-21 07:52 UTC, eggerdj commented on qiskit_cold_atom/synqs_fermions/__init__.py
> +from .fqs_gate_library import (
We should use the existing gates as much as possible and if something is lacking from those we should extend the library.

2021-12-03 15:27 UTC, fretchen commented
I think that this one can be closed as it is now superseeded by #13

2021-12-06 17:21 UTC, fretchen commented
I pushed the discussed changes. However, one important problem remains. QISKIT is not working with the interleaved notation, while other frameworks and our back-end do. @RohitPrasadBhatt therefore suggested to create a flag in the config that allows to notify the backend which kind of notation it receives for fermionic devices and also to say which kind of notation it expects. I fully support this idea. Should this be an extra issue ?

2021-12-08 09:35 UTC, merged