Make it possible to perform LxLy rotations
Qiskit-Extensions/qiskit-cold-atom pull request #8
Opened 2021-09-30 05:26 UTC by fretchen

Proposal to implement the LxLy gate

2021-09-30 10:26 UTC, eggerdj requested changes
This looks good. Would it be possible to add a test, e.g. something like this? https://github.com/Qiskit-Extensions/qiskit-cold-atom/blob/b194142da8c9ed34566ae708b6f2c7350364fd7a/test/test_spin_gates.py#L35-L62

2021-09-30 10:26 UTC, eggerdj commented on qiskit_cold_atom/spins/spins_gate_library.py
> +    r"""The spin exchange gate o two collective spins.
```suggestion
    r"""The spin exchange gate of two collective spins.
```

2021-10-01 05:52 UTC, fretchen commented
Done. However, I was not try to find any indication anywhere on how to run the tests locally.

2021-10-01 08:59 UTC, LaurinFischer commented
Hi Fred, this looks good, thanks. To run the tests, simply run 
```
python -m unittest 
```
from the repository root. (I added this to the Readme, thanks for pointing out.)

2021-10-01 09:21 UTC, fretchen commented
So when I ran the test I found some issues with how I had implemented it and now it also uses `np.allclose()`. However, the tests fail as I did not add the Heidelberg provider credentials:

```
% python -m unittest
/qiskit-cold-atom/qiskit_cold_atom/providers/cold_atom_provider.py:289: UserWarning: No credentials found at the specified location
  warnings.warn("No credentials found at the specified location")
```

This is most likely an independent issue, but I it is somehow not obvious that this is good as I think that I mostly followed the most basic installation rules...

2021-10-01 09:36 UTC, LaurinFischer commented
Hi Fred, I opened a new issue for the behaviour of the credentials in the test suite. I'm not sure what's going on as the test is designed such that it creates some dummy credentials on the fly and then deletes them afterwards. 
Do your test fail or is it just this warning which is being triggered? Maybe you could post the entire output of your console in the discussion of the issue #10

2021-10-01 13:30 UTC, eggerdj approved these changes
Looks good to me.

2021-10-01 13:32 UTC, merged